-- MySQL Script generated by MySQL Workbench
-- 03/22/18 11:01:41
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BaseReservaNew
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BaseReservaNew
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BaseReservaNew` DEFAULT CHARACTER SET utf32 ;
USE `BaseReservaNew` ;

-- -----------------------------------------------------
-- Table `BaseReservaNew`.`habitación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseReservaNew`.`habitación` (
  `idhabitación` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(4) NOT NULL,
  `piso` VARCHAR(2) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `caracteristicas` VARCHAR(512) NULL,
  `precio_diario` DOUBLE NOT NULL,
  `estado` VARCHAR(45) NULL,
  `precio_x3h` DOUBLE NOT NULL,
  `precio_xh` DOUBLE NOT NULL,
  `habitacióncol` VARCHAR(45) NULL,
  PRIMARY KEY (`idhabitación`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseReservaNew`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseReservaNew`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(20) NOT NULL,
  `apaterno` VARCHAR(20) NOT NULL,
  `amaterno` VARCHAR(20) NOT NULL,
  `tipo_documento` VARCHAR(15) NOT NULL,
  `num_documento` VARCHAR(8) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `telefono` VARCHAR(8) NULL,
  `email` VARCHAR(25) NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseReservaNew`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseReservaNew`.`trabajador` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `sueldo` DOUBLE NOT NULL,
  `acceso` VARCHAR(15) NULL,
  `login` VARCHAR(15) NULL,
  `password` VARCHAR(20) NULL,
  `estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idpersona`),
  CONSTRAINT `fk_persona_trabajador`
    FOREIGN KEY (`idpersona`)
    REFERENCES `BaseReservaNew`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `BaseReservaNew`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseReservaNew`.`cliente` (
  `idpersona` INT NOT NULL,
  `codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `codigo_cliente_UNIQUE` (`codigo_cliente` ASC),
  CONSTRAINT `fk_persona_cliente`
    FOREIGN KEY (`idpersona`)
    REFERENCES `BaseReservaNew`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseReservaNew`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseReservaNew`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `unidad_medida` VARCHAR(20) NOT NULL,
  `precio_venta` DOUBLE NOT NULL,
  `stock` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseReservaNew`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseReservaNew`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `idhabitacion` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `idtrabajador` INT NOT NULL,
  `dia` INT NOT NULL,
  `mes` INT NOT NULL,
  `ano` INT NOT NULL,
  `hora_ingreso` VARCHAR(10) NOT NULL,
  `hora_salida` VARCHAR(10) NOT NULL,
  `salida_real` VARCHAR(10) NOT NULL,
  `costo_alojamiento` DOUBLE NOT NULL,
  `estado_reserva` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_habitacion_idx` (`idhabitacion` ASC),
  INDEX `fk_reserva_cliente_idx` (`idcliente` ASC),
  INDEX `fk_reserva_trabajador_idx` (`idtrabajador` ASC),
  CONSTRAINT `fk_reserva_habitacion`
    FOREIGN KEY (`idhabitacion`)
    REFERENCES `BaseReservaNew`.`habitación` (`idhabitación`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `BaseReservaNew`.`cliente` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_trabajador`
    FOREIGN KEY (`idtrabajador`)
    REFERENCES `BaseReservaNew`.`trabajador` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseReservaNew`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseReservaNew`.`consumo` (
  `idconsumo` INT NOT NULL AUTO_INCREMENT,
  `idreserva` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `cantidad` DOUBLE NULL,
  `precio_venta` DOUBLE NULL,
  `estado` INT NULL,
  PRIMARY KEY (`idconsumo`),
  INDEX `fk_consumo_producto_idx` (`idproducto` ASC),
  INDEX `fk_consumo_reserva_idx` (`idreserva` ASC),
  CONSTRAINT `fk_consumo_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `BaseReservaNew`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_reserva`
    FOREIGN KEY (`idreserva`)
    REFERENCES `BaseReservaNew`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseReservaNew`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseReservaNew`.`pago` (
  `idpago` INT NOT NULL,
  `idereserva` INT NOT NULL AUTO_INCREMENT,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `num_comprobante` INT NOT NULL,
  `igv` DOUBLE NOT NULL,
  `total_pago` DOUBLE NOT NULL,
  `fecha_emision` VARCHAR(10) NOT NULL,
  `fecha_pago` VARCHAR(10) NOT NULL,
  `hora_pago` VARCHAR(10) NOT NULL,
  `subtotal` DOUBLE NOT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_pago_reserva_idx` (`idereserva` ASC),
  CONSTRAINT `fk_pago_reserva`
    FOREIGN KEY (`idereserva`)
    REFERENCES `BaseReservaNew`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseReservaNew`.`Regasis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseReservaNew`.`Regasis` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `fecha_entrada` VARCHAR(10) NOT NULL,
  `hora_entrada` VARCHAR(10) NOT NULL,
  `hora_salida` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idpersona`),
  CONSTRAINT `fk_registro_trabajador`
    FOREIGN KEY (`idpersona`)
    REFERENCES `BaseReservaNew`.`trabajador` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseReservaNew`.`limpieza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BaseReservaNew`.`limpieza` (
  `idlimpieza` INT NOT NULL AUTO_INCREMENT,
  `reserva_idreserva` INT NOT NULL,
  PRIMARY KEY (`idlimpieza`),
  INDEX `fk_limpieza_reserva1_idx` (`reserva_idreserva` ASC),
  CONSTRAINT `fk_limpieza_reserva1`
    FOREIGN KEY (`reserva_idreserva`)
    REFERENCES `BaseReservaNew`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
